kubeconfig changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,9 +16,9 @@ jobs:
 
     - name: Check required secrets
       run: |
-        test -n "${{ secrets.DOCKER_USERNAME }}" || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
-        test -n "${{ secrets.DOCKER_PASSWORD }}" || (echo "Missing DOCKERHUB_PASSWORD" && exit 1)
-        test -n "${{ secrets.KUBECONFIG_DATA }}" || (echo "Missing KUBECONFIG_DATA" && exit 1)
+        test -n "${{ secrets.DOCKER_USERNAME }}" || (echo "Missing DOCKER_USERNAME" && exit 1)
+        test -n "${{ secrets.DOCKER_PASSWORD }}" || (echo "Missing DOCKER_PASSWORD" && exit 1)
+        test -n "${{ secrets.KUBECONFIG_B64 }}" || (echo "Missing KUBECONFIG_B64" && exit 1)
 
     - name: Set up environment
       run: echo "PATH=$PATH:$HOME/bin" >> $GITHUB_ENV
@@ -26,7 +26,7 @@ jobs:
     - name: Set up Kubeconfig
       run: |
         mkdir -p $HOME/.kube
-        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
+        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
         chmod 600 $HOME/.kube/config
         export KUBECONFIG=$HOME/.kube/config
         kubectl version --client
