changed DOCEKRHUB to DOCKER

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,8 +16,8 @@ jobs:
 
     - name: Check required secrets
       run: |
-        test -n "${{ secrets.DOCKERHUB_USERNAME }}" || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
-        test -n "${{ secrets.DOCKERHUB_PASSWORD }}" || (echo "Missing DOCKERHUB_PASSWORD" && exit 1)
+        test -n "${{ secrets.DOCKER_USERNAME }}" || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
+        test -n "${{ secrets.DOCKER_PASSWORD }}" || (echo "Missing DOCKERHUB_PASSWORD" && exit 1)
         test -n "${{ secrets.KUBECONFIG_DATA }}" || (echo "Missing KUBECONFIG_DATA" && exit 1)
 
     - name: Set up environment
@@ -36,13 +36,13 @@ jobs:
         sudo nerdctl build -t tanvi-python-app:latest .
 
     - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo nerdctl login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo nerdctl login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
     - name: Tag Docker image
-      run: sudo nerdctl tag tanvi-python-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/tanvi-web:latest
+      run: sudo nerdctl tag tanvi-python-app:latest ${{ secrets.DOCKER_USERNAME }}/tanvi-web:latest
 
     - name: Push Docker image
-      run: sudo nerdctl push ${{ secrets.DOCKERHUB_USERNAME }}/tanvi-web:latest
+      run: sudo nerdctl push ${{ secrets.DOCKER_USERNAME }}/tanvi-web:latest
 
     - name: Deploy to Kubernetes
       run: |
